#pragma once

#include "CoreMinimal.h"

namespace URSoccerLab
{
/** Normalizes component names generated by imported Blueprint instances. */
class URSOCCERLAB_API FRobotNames
{
public:
	static FString NormalizeImportedComponentName(const FString& Name);
	static FString NormalizeRobotComponentName(const FString& Name, const FString& RobotName);
};
} // namespace URSoccerLab
